### ISSUE TITLE
Full phpspec tests

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#1]
See https://github.com/ddeboer/data-import/pull/215.

**Comment by sagikazarmark** [comment]
Assign me to this

**Comment by sagikazarmark** [comment]
I can't assign myself for some reasons.

**Comment by ddeboer** [comment]
And I can’t assign you either, no clue as to why not.

**Comment by sagikazarmark** [comment]
Ah, found it. It was because of visibility.

**Comment by ddeboer** [comment]
No, it’s because you have to be a collaborator on the repo. Just made you one. :)

**Comment by sagikazarmark** [comment]
Ah, I see.

**Comment by ddeboer** [comment]
I see no reason anymore to switch from PHPUnit to phpspec, so closing this.
