### ISSUE TITLE
Nice structures but GUI?

### ISSUE THREAD

**Issue by rokondo** [portphp/portphp#102]
The code is very nice structured and extensible. But I want to create for some more sources pattern for imports and want to organize them in a database and let people configure. Is there a example with a GUI or is something planned like this?

**Comment by ddeboer** [comment]
Hi @rokondo, thanks for your kind words. Setting up data exports/imports using PortPHP is purely code-driven; we don’t have a GUI planned. If you want to work on one, however, you’d be more than welcome. 😄
