### ISSUE TITLE
JSON import

### ISSUE THREAD

**Issue by applibs** [portphp/portphp#103]
I can not find how to import file with JSON content.
Exists any solution with included readers?

**Comment by courtney-miles** [comment]
I would guess this would work...

```php
$reader = new ArrayReader(
    json_decode(
        file_get_contents('data.json'),
        true
    )
);
```

**Comment by Baachi** [comment]
@courtney-miles is correct. You can simply use `json_decode` and then pass it to the `ArrayReader`. Please be aware, that this could potentially lead to memory leaks because you write the entire file into memory.
