### ISSUE TITLE
I tried to upgrade to Symfony 5 and received  an "Your requirements could not be resolved to an installable set of packages." message

### ISSUE THREAD

**Issue by ingcarlosperez** [portphp/portphp#106]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/translation 5.0.* -> satisfiable by symfony/translation[v5.0.0, v5.0.1].
    - portphp/steps 1.2.2 requires symfony/validator ^2.5 || ^3.0 || ^4.0 -> satisfiable by symfony/validator[v4.4.1].
    - portphp/steps 1.2.0 requires symfony/validator ^2.5 || ^3.0 || ^4.0 -> satisfiable by symfony/validator[v4.4.1].
    - portphp/steps 1.2.1 requires symfony/validator ^2.5 || ^3.0 || ^4.0 -> satisfiable by symfony/validator[v4.4.1].
    - portphp/steps 1.2.2 requires symfony/validator ^2.5 || ^3.0 || ^4.0 -> satisfiable by symfony/validator[v4.4.1].
    - Conclusion: remove symfony/validator v4.4.1
    - Installation request for portphp/steps ^1.2 -> satisfiable by portphp/steps[1.2.0, 1.2.1, 1.2.2].

**Comment by ddeboer** [comment]
Fixed! Please try again. 😁
