### ISSUE TITLE
How to Generate an Excel file response (attachment)?

### ISSUE THREAD

**Issue by Nugjii** [portphp/portphp#107]
I am using PortPHP in symfony 4. In the export data to excel section of my system, i have no idea about generate an Excel file response (attachment). SpreadsheetWriter ask SplFileObject in constructor but i do not want to save excel file in my server. I read all the docs and googled but can not found any solution. What is the right solution, please help.

**Comment by Baachi** [comment]
Hey @Nugjii,

sorry for the late response! PHP supports writing files to the memory or in a temporary file through a stream.

Here is an quick example:

```
$file = new \SplFileObject('php://temp', 'a+'); // Temporary file
$file = new \SplFileObject('php://memory', 'a+'); // Memory
$file->fwrite('Foo');

$file->rewind();

while (!$file->eof()) {
    echo $file->fread(4096);
}
```

Here is the documentation from php. 
https://www.php.net/manual/de/wrappers.php.php
