### ISSUE TITLE
Project - still alive and maintained

### ISSUE THREAD

**Issue by klodoma** [portphp/portphp#110]
I just want to ask if someone is still using/taking care of this packages and if this project is still alive. 

I see some potential, but I see also issues and I would like to know if I ride here a dead horse or not. 

Thanks

**Comment by klodoma** [comment]
+17 days ago :)

Question answered.

**Comment by ddeboer** [comment]
Unfortunately I don’t have much time for maintaining this package. While PortPHP is helping developers that need to move data around, my use cases for it at this moment are limited. 

So to anyone reading this: please let me know if you’d like to help out in maintaining PortPHP! 😄

**Comment by klodoma** [comment]
Hi @ddeboer . Thank you for answering. 
It's ok, we're all under time pressure in a way or another. 

I am currently playing around with these; I have a good use-case where I use PortPHP to import some data and I already updated some packages in my forks(at least the package versions, unit-tests and so on). I have also made some improvements to the DoctrineWriter. It's a bit specific for my use-case but, it's an open discussion. 

One good first step is to upgrade all the "dependencies", so that we clean-up these old dependencies. I am already working on this. 

Do you want to work with PR or you could give me direct access in the repos, I could push some branches. 

I don't have full time, but at least with the changes I do, I could contribute.

**Comment by ddeboer** [comment]
@klodoma Cool!

If that’s okay with you, could you please start with submitting PRs? If that works out well, I have no problems giving you write access.

**Comment by klodoma** [comment]
Ok. I will! Let me finish the stuff first 👍 I'll close this issue now.
