### ISSUE TITLE
CsvReader and CsvWriter have different default delimiters

### ISSUE THREAD

**Issue by deviantintegral** [portphp/portphp#113]
Comparing:

https://github.com/portphp/csv/blob/master/src/CsvReader.php#L82

to

https://github.com/portphp/csv/blob/master/src/CsvWriter.php#L43

We can see that the reader class uses a comma (`,`) as it's default delimiter, while the writer class uses a semicolon (`;`). This makes for a confusing developer experience as you'd expect both classes to have the same defaults.

**Comment by ddeboer** [comment]
Fixed in portphp/csv 2.0.1.
