### ISSUE TITLE
Conflicts with other doctrine packages

### ISSUE THREAD

**Issue by yahyaakli** [portphp/portphp#116]
Hello,
I am using the latest version of Symfony and doctrine, and apparently, there is a conflict between Port Doctrine and other doctrine packages.
Port Doctrine requires common 2.2
`"require": {
        "php": ">=5.6.0",
        "portphp/portphp": "^1.0.0",
        "doctrine/common": "^2.2"
    },`
whereas Doctrine cache conflicts with that:
`  "conflict": {
        "doctrine/common": ">2.2,<2.4"
    },`

when I try to install it I get errors, what should I do?

**Comment by juan-Pc** [comment]
Tengo el mismo problema :(

**Comment by ddeboer** [comment]
Fixed with portphp/doctrine 1.2.0 (https://github.com/portphp/doctrine/pull/18).
