### ISSUE TITLE
Please tag new release of portphp/pdo

### ISSUE THREAD

**Issue by dawehner** [portphp/portphp#117]
It would be great to tag a new release of portphp/pdo, as this includes a quite important bug fix, see https://github.com/portphp/pdo/compare/1.0.0...master

Given this is a bugfix only I think a patch version release would be enough: `1.0.1`

Let me know what you think

**Comment by ddeboer** [comment]
Tagged as 1.0.1, thanks!

**Comment by dawehner** [comment]
Thank you @ddeboer
