### ISSUE TITLE
\SplFileObject::READ_AHEAD | issue with PHP 8

### ISSUE THREAD

**Issue by gomcodoctor** [portphp/portphp#118]
CsvReader has flag \SplFileObject::READ_AHEAD, its causing issue with PHP 8

**Comment by czoIg** [comment]
Fix: https://github.com/portphp/csv/pull/7

**Comment by olimination** [comment]
Hi @ddeboer ,

would it be possible to merge the PR of @czoIg? This solved my issue at least for the Sylius ImportExportPlugin.

I have also done quickly some research according to your question and I have found this one: https://bugs.php.net/bug.php?id=62004

As far as I understand the code change in this mentioned PHP issue, there have been some changes in the "seek" method which is in use with this `rewind()` method mentioned in this ticket here. I assume this changed then the behaviour. What do you think?

**Comment by ddeboer** [comment]
Thanks for reporting! It seems this bug was [fixed in PHP 8.0.1](https://bugs.php.net/bug.php?id=62004), so closing this. Please report here if you still encounter the problem.

**Comment by olimination** [comment]
Thanks @ddeboer for the hint. I have tested it once again with PHP 8.0.16 and portphp/csv 2.0.1 and the Sylius ImportExport plugin worked properly. See also the closed issue here: https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/271.
