### ISSUE TITLE
The DuplicateHeadersException uses implode with an incorrect parameter order

### ISSUE THREAD

**Issue by williameggers-catch-e** [portphp/portphp#123]
The DuplicateHeadersException uses implode with an incorrect parameter order (as of PHP 7.4.0, removed in PHP 8.0.0).

I'm getting the following exception thrown in unit tests for one of my projects being upgraded to PHP 8.0.

`TypeError: implode(): Argument #2 ($array) must be of type ?array, string given`

Trace:

vendor/portphp/portphp/src/Exception/DuplicateHeadersException.php:15
vendor/portphp/csv/src/CsvReader.php:338
vendor/portphp/csv/src/CsvReader.php:187

**Comment by ddeboer** [comment]
Thanks for reporting! Fixed in version 1.6.1.
