### ISSUE TITLE
Package separation

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#16]
Looking at the main package only DBAL and PDO related stuff remained which are not some sort of simple implementation (like array reader). So I think those should also go into their own adapter, so that the main package can be some sort of contract.

The only question: what should be done with Filters and ValueConverters? Actually, they don't really make sense without the steps package...

**Comment by ddeboer** [comment]
Created https://github.com/portphp/dbal-adapter and https://github.com/portphp/pdo-adapter. I’ll split the code from the main package and push it to the separate repos.
