### ISSUE TITLE
Middleware architecture

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#17]
I am reopening this as I think it is a really good idea.

ddeboer/data-import#227

In case of a middleware architecture there is no need to specify steps like filter and converter as in a middleware you are free to break the chain or modify the item passed to the next middleware. (This does not mean we can't, it only means that we don't need, I am especially referring to the return value behavior, namely true means continue, false means filter out in steps)

**Comment by sagikazarmark** [comment]
It would also ease creating a pipeline (like in plum).

**Comment by ddeboer** [comment]
And this could be an alternative workflow to steps. So we gave a step-based workflow and a middleware-based workflow. Or we implement the steps themselves as middleware, to make them more flexible.

**Comment by sagikazarmark** [comment]
I am in favor of the latter. I think the public API would not really change, only internals would change.
