### ISSUE TITLE
League Console adapter

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#18]
I would like to implement the console-adapter for CLImate (presented by the PHP League)

So we should either rename the current console-adapter to symfony-console-adapter (prefer this) or implement both in one package and suggest.

**Comment by sagikazarmark** [comment]
Also, the after renaming the console adapter should be added to scrutinizer and packagist. I cannot add them, as I cannot update the Webhooks.

**Comment by ddeboer** [comment]
Most packages aren’t yet added on [Packagist](https://packagist.org/search/?q=portphp), on purpose (until the names have settled down). 

https://github.com/portphp/league-console-adapter
https://github.com/portphp/symfony-console-adapter

**Comment by sagikazarmark** [comment]
Any idea for namespace? `Port\Console` is ambiguous this way.

`Port\SymfonyConsole`
`Port\Symfony\Console`
`Port\Symfony`...(ConsoleProgressWriter)

(and the same alternatives for the League)

**Comment by ddeboer** [comment]
`Port\Symfony|LeagueConsole` makes most sense to me.

**Comment by sagikazarmark** [comment]
Maybe we could leave the `Console` prefix from `ConsoleProgressWriter` and `ConsoleTableWriter` now, that they are in a separate package.
