### ISSUE TITLE
Doctrine performance

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#19]
Maybe we could cross-check with the [official documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/batch-processing.html#iterating-large-results-for-data-processing) for large data processing.

**Comment by ddeboer** [comment]
This logic was in the DoctrineWriter but has been moved to the BatchWriter for improved re-usability.

**Comment by sagikazarmark** [comment]
Ah, fine.
