### ISSUE TITLE
Package namespaces

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#2]
Which do we prefer?

1. `Port\Reader\Csv` and `Port\Writer\Csv`
1. `Port\Csv\Reader` and `Port\Csv\Writer`
1. `Port\Csv\CsvReader` and `Port\Csv\CsvWriter`

I think it’s a best practice to have one namespace per package (yields faster autoloading?) so I’m slightly in favour of 2 or 3.

**Comment by sagikazarmark** [comment]
From a single package point of view 2. is probably nicer. But I think in many cases we would end up doing the following: `use Port\Csv\Reader as CsvReader;`

**Comment by sagikazarmark** [comment]
Oh, I guess it is because group permissions. I hate that Github only have three types of permissions.

**Comment by ddeboer** [comment]
> But I think in many cases we would end up doing the following: use Port\Csv\Reader as CsvReader;

Exactly, so that's why maybe just having `Port\Excel\ExcelReader` is easier, as it requires less aliasing. I opted for this method in our excel package, and stuck to `Port\Csv\Reader` in the csv one. See which one you like best, also @Baachi, and we’ll decide one way or the other.

**Comment by sagikazarmark** [comment]
Requires less aliasing and easier to read.

**Comment by Baachi** [comment]
I would use option 1, its the easiest way for developers and doesn't require to alias each name.

**Comment by sagikazarmark** [comment]
> and doesn't require to alias each name.

Not true, Csv itself is a collision.

**Comment by Baachi** [comment]
Sure thats true but read from a csv file and write down to a csv file is a really rare usecase. But for sure we can also use option 3, that wouldn't require any aliasing. (FYI [flysystem](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php) use also option 3).

**Comment by sagikazarmark** [comment]
@Baachi you can never know ;) I was forced once to transform CSV into CSV.

:+1: option 3

**Comment by Baachi** [comment]
I only said its a rare use case not nobody does this. So for me i vote for __option 3__, too.

**Comment by sagikazarmark** [comment]
Yeah, sure. ;)

Me too (option 3).

**Comment by ddeboer** [comment]
Option 3 it is!
