### ISSUE TITLE
XML Writer implementation

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#22]
I have a deadly simple XML Writer implementation. Should it go into the main package or a separate one?

Based on #16, I think it is the latter.

**Comment by ddeboer** [comment]
Created https://github.com/portphp/xml-adapter. Please push your code there. :smile:

**Comment by applibs** [comment]
What about XML Reader please?

**Comment by ddeboer** [comment]
We don’t have one now @applibs. Would you be able to contribute one?

**Comment by applibs** [comment]
No time and knowledge to do it.
