### ISSUE TITLE
Remove getFields from Reader

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#27]
Where is it used exactly? Because I can't find any usage.

AFAIK it was used with the "old" Converter structure, but it isn't used now.

So can we just get rid of it? I think it causes a lot of trouble, especially with readers using an underlying iterator.

If we are going to have Item objects discussed in #14 it can directly be added to Item objects.

**Comment by sagikazarmark** [comment]
ping @ddeboer @Baachi :)

**Comment by Baachi** [comment]
From my POV it can be removed. The method hasn't any value anymore.
