### ISSUE TITLE
Do we need a pagefanta adapter?

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#28]
I've just found this package:

https://github.com/adrienbrault/pagerfanta-iterator

It basically does the same as our pagerfanta reader but in a more generic way: iterates through all elements using paging while exposing an Iterator. Since we already have an iterator reader, I wonder if we should drop the original plan to create a pagerfanta-adapter and recommend to use this package. This way we can just "remain in the dark" and rely on our tiny IteratorReader.

**Comment by ddeboer** [comment]
Good idea!

**Comment by sagikazarmark** [comment]
I am still looking at the implementation, but as a start it is good. I might have a few suggestions for the author to make it better.

I am going to deprecate the pagerfanta-adapter. I would rather not delete it completely, since it is a good example. We should simply not publish it to packagist.

**Comment by sagikazarmark** [comment]
@ddeboer Can you put the `[DEPRECATED]` mark in the beginning of the description?

**Comment by ddeboer** [comment]
Done.
