### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#3]
* ~~convert to reST~~
* review current functionality and make sure it is all documented
* add a quickstart section with some easy examples.

**Comment by ddeboer** [comment]
See https://github.com/ddeboer/data-import/issues/148, https://github.com/ddeboer/data-import/issues/196.

**Comment by sagikazarmark** [comment]
ddeboer/data-import#208

**Comment by sagikazarmark** [comment]
It seems to me that RTD supports markdown as well. Are there any reasons why reStructuredText is better?

**Comment by ddeboer** [comment]
Yeah, I just found that out by accident because RTD defaulted to Markdown. 

Actually, let's try Mkdocs instead of reST, as it's better to have one syntax for all documents (readme, docs, etc.). It seems cross references are possible. The only thing missing may be including other files, which may be useful for including tested .php (so no spelling errors or other mistakes) from the tests directory into the docs. However, as our tests will be divided over many repos and our docs available only in the main repo, I'm not so sure we will be needing this feature.

**Comment by sagikazarmark** [comment]
:+1: Actually, I am planning to use RTD for PHP HTTP as well. ;) reST was my only concern.

**Comment by ddeboer** [comment]
Please continue discussion in #12.
