### ISSUE TITLE
Make progress

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#31]
Hey guys,

I would like to make progress with the package. Now that Httplug seems to be finished or at least we reach a first stable, I would like to spend some time with other OSS projects. (Especially because it seems I might get paid for it at my regular job)

Apart from coding, here are the few points I would like to do:
- Not sure if we already have a domain, it seems portphp.org it is
- I would like to hire a designer to make us a logo
- I would like to set up a slack account for us (httplug/php-http also moved from gitter to slack)

Coding tasks:
- Finalize the API
- Migrate the rest of the code from data-import

**Comment by Baachi** [comment]
Hey @sagikazarmark, this would be really appreciated! 

I would prefer to migrate all code from data-import to portphp before we finalize the code and implement new features. 
I don't know if it helps to move to slack but i'm not against it (as a side note: i don't have slack because i use ubuntu).

> Especially because it seems I might get paid for it at my regular job

Congratulation! Your living a dream :fireworks:

**Comment by sagikazarmark** [comment]
> I would prefer to migrate all code from data-import to portphp before we finalize the code and implement new features.

Is there anything that is not migrated yet? Also, by finalizing I mean stabilizing the interface which is necessary for the rest of the project anyway

> i don't have slack because i use ubuntu

There is scudcloud which is awesome, but there are official beta slack clients for ubuntu/linux as well.

**Comment by ddeboer** [comment]
@sagikazarmark Great if you can give this library some attention! Unfortunately, I’ve been real busy lately and haven’t had the time to give open source projects the attention they deserve.

To the list of tasks that we need done before our first I’d add:
- [ ] documentation, including a ‘Getting started’ chapter

The domain is indeed portphp.org; I suggest we keep the website simple, or maybe just a redirect to our docs for now.

**Comment by sagikazarmark** [comment]
@ddeboer I would set up a slack account for us if you are OK with that. I would also set up slackin, which allows us to make slack publicly available (see http://slack.httplug.io).

I agree with the website, you could check what I did for Httplug (http://httplug.io)

**Comment by ddeboer** [comment]
Slack is fine!

**Comment by sagikazarmark** [comment]
Email addresses please, so I can invite you.

The public URL:

https://portphp-slack.herokuapp.com/

@ddeboer Can you create a CNAME slack.portphp.org to this domain?

**Comment by ddeboer** [comment]
I was able to join directly on Slack by filling in my e-mail address.

CNAME: done.

**Comment by Baachi** [comment]
> Is there anything that is not migrated yet? Also, by finalizing I mean stabilizing the interface which is necessary for the rest of the project anyway

All PRs which have been opened on the PR.

> There is scudcloud which is awesome, but there are official beta slack clients for ubuntu/linux as well.

Ah didn't know that, i will give it a try

**Comment by sagikazarmark** [comment]
Cool, added you as admins.

**Comment by ddeboer** [comment]
All communication channels setup; also merged most of things that we need before 1.0. We can discuss the details in the individual issues/PRs.
