### ISSUE TITLE
Organizational tasks

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#4]
- [x] Create Scrutinizer group
- [x] Create Packagist user
- [x] Create organizational Gitter room
- [x] Countributing doc
- [x] Enable Travis builds

**Comment by sagikazarmark** [comment]
I can do all of these if you would like to me to do it.

**Comment by sagikazarmark** [comment]
I meant an organizational Gitter room, that one is for the main repo. I can't create it since I am not an owner.

**Comment by ddeboer** [comment]
We now have both.
