### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#44]
We now have:

- portphp/doctrine-adapter
- portphp/pdo-adapter
- portphp/csv-adapter

While doctrine-adapter makes sense, as it’s an adapter for the Doctrine library, this is not the case for pdo- and csv-adapter. These are just reader/writer combinations. What about giving all packages shorter names like: doctrine, pdo and csv?

**Comment by sagikazarmark** [comment]
As far as I remember we decided having the -adapter suffix to separate packages and "packages that are extensions of portphp" (readers/writers/filters/etc), but I am all for shorter names, there is a short description on Github and Packagist anyway.

**Comment by ddeboer** [comment]
Cool, switching to the short package names.
