### ISSUE TITLE
Doctrine adapter composer

### ISSUE THREAD

**Issue by lalop** [portphp/portphp#45]
Hello,
I wanted to test portphp but I can't find portphp/doctrine or protphp/doctrine-adapter on composer.
Is that normal ?

Thank you

**Comment by ddeboer** [comment]
Whoops, you’re completely right! I added the package to Packagist.

**Comment by lalop** [comment]
so is it doctrine or doctrine-adapter ?

**Comment by ddeboer** [comment]
It’s [portphp/doctrine](https://packagist.org/packages/portphp/doctrine) (also mentioned in the [docs](https://portphp.readthedocs.io/en/latest/readers/#doctrine-ormodm)).

**Comment by lalop** [comment]
so this readme is wrong https://github.com/portphp/doctrine

**Comment by ddeboer** [comment]
Fixed!
