### ISSUE TITLE
Stable Release Timeline

### ISSUE THREAD

**Issue by KorvinSzanto** [portphp/portphp#46]
What's the plan for v1.0.0? We hope to use this library in the next stable release of concrete5, is there any way we can help get this project stable?

**Comment by KorvinSzanto** [comment]
@ddeboer, should I just attempt to contribute code for the issues in the v1.0 milestone?

**Comment by sagikazarmark** [comment]
Hi @KorvinSzanto 

There are a few points which (break the current API and) are needed to be cleared before 1.0.

One thing is the matter of payloads (typehint, custom DTO, etc). There are quite a few ideas, but no solution yet.

Once those are cleared and we reviewed the API, I think we can tag 1.0.

**Comment by sagikazarmark** [comment]
Can I ask what the use case is in concrete5 which this library would solve?

**Comment by KorvinSzanto** [comment]
I wasn't involved in the feature creation, I'm just trying to get composer stable. Here's the issue that originally requested it: https://github.com/concrete5/concrete5/issues/5081
