### ISSUE TITLE
When using the Doctrine Writer Create Entity and relationship

### ISSUE THREAD

**Issue by emudojo** [portphp/portphp#49]
I have 1 single file that needs to be imported
each row has to split in 3 different entities, how can I do that when using the Workflow ? the writer only receives an instance of the writer... and I don't know how to map the original CSV file to aggregate fields per entity

**Comment by jeroendk** [comment]
Hi @emudojo did you figure out how to do this ? I need this to.

**Comment by Baachi** [comment]
Hey @jeroendk 

sorry for the late response? Do you want to map associations? Then the ItemConverter should resolve your problem.

**Comment by jeroendk** [comment]
@Baachi No problem, yes i wanted to map one row to multiple **new** entities with associations.
Currently solved it with a custom import step and php code.

Does the ItemConverter works with new objects ? Is there a example available ?

**Comment by Baachi** [comment]
Ah so you want to create more than one entity from one row. I thought you create one entity with mutliple associations from one row. Sorry!

This doesn't work out ot the box. 

So the best way is to create a seperate step, indeed.

**Comment by jeroendk** [comment]
Alright, thanks!
