### ISSUE TITLE
can we get a release?

### ISSUE THREAD

**Issue by OskarStark** [portphp/portphp#52]

**Comment by ddeboer** [comment]
Just released portphp/portphp and steps 1.0.0.

**Comment by OskarStark** [comment]
good job, thank you 👍

**Comment by OskarStark** [comment]
If you are on it, can you please release csv, too? otherwise I could not install it:

![screenshot 2017-08-30 10 01 36](https://user-images.githubusercontent.com/995707/29861657-399247fc-8d6a-11e7-9247-e9352c214baa.png)

**Comment by ddeboer** [comment]
Done.

**Comment by OskarStark** [comment]
Thank you!

**Comment by OskarStark** [comment]
Works like a charme!
