### ISSUE TITLE
Using validation annotations in doctrine entity

### ISSUE THREAD

**Issue by Glideh** [portphp/portphp#57]
When using a doctrine writer, is there a way to take advantage of the doctrine annotations already there ?

```php
// Doctrine entity class
/**
 * @var string
 *
 * @ORM\Column(type="string", length=150, nullable=false)
 * @Assert\NotBlank
 */
private $name;
```

So we don't have to redefine them in a `ValidatorFilter`.
Or do we have to use reflection to inject them into `ValidatorFilter`s ?

**Comment by ddeboer** [comment]
You’re talking about the `@Assert\NotBlank`, right? Actually, that’s not Doctrine-specific, but a more generic (Symfony) validation constraint.

What you’re then asking for, is a way to validate some PHP object with annotations. This should be as simple as:

```php
$errors = $validator->validate($yourObject);
```

Perhaps we could add this to our `ValidatorStep`.

**Comment by Glideh** [comment]
I forgot these constraints were Symfony ones.
Using a `StepAggregator` where can I validate the object already transformed ?
I could override `__invoke` in `ValidatorFilter` but it receives the array.
