### ISSUE TITLE
Migrate steps to a separate package

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#6]

**Comment by sagikazarmark** [comment]
Removed step details in remove/steps branch

**Comment by ddeboer** [comment]
One question I have about this: will steps require portphp/portphp? I prefer the other way around: portphp/portphp shipping with Steps as default Workflow implementation. That way, users can get up and running more quickly.

**Comment by sagikazarmark** [comment]
What do you propose? Leave the workflow in portphp/portphp and require portphp/steps?

**Comment by ddeboer** [comment]
Actually, no, that will become a mess. According to dependency inversion, the way it is now is the right one (steps depending on portphp). So let’s leave it like this, and explain in the docs that users need to install portphp/steps separately. (Of course this makes more sense when we have other implementations of the workflow, too.)

**Comment by ddeboer** [comment]
See https://github.com/portphp/steps/pull/1.
