### ISSUE TITLE
Symfony deprecation

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/portphp#7]
During running unit tests I noticed two errors:

1. Validator class is deprecated from version 2.5
2. True constraint is deprecated from 2.7

I wonder if the dependency should be moved up or not. At least the dev dependencies are moved up. See the inital import of steps and the symfony_deprecation branch here.

**Comment by Baachi** [comment]
Thats true, i leaved it to be compatible with symfony `< 2.5`

**Comment by sagikazarmark** [comment]
So how should we proceed? Looking at the code, the interfaces are the same, so probably only the actual testing code was not compatible with newer versions which means the code still can be compatible with `< 2.5`, but should not be tested against it. Others will also get these warnings.

**Comment by Baachi** [comment]
There are only two ways, we can bump up the symfony requirements to `2.5` and doesn't support symfony 2.3 anymore. 

Or create a new class `Symfony27ValidatorStep` and use the new interface.

**Comment by sagikazarmark** [comment]
Currently there are no hard requirement of any symfony packages, they are only development dependencies.

**Comment by Baachi** [comment]
I know, this validator should be compatible with any symfony version. The problem is, the symfony/validator component changes a lot in version 2.5, so we generate a lot of deprecation notices.

Whats your suggestion?

**Comment by sagikazarmark** [comment]
As I said, I think the interface itself is not changed, only the implementation, so compatibility should not be an issue IMO. Symfony will trigger these warnings anyway. So as long as the interface is really compatible (and I think it is) we should just do nothing. :stuck_out_tongue_winking_eye: 

What we can do is to test against the lowest possible version (which means there is no deprecation/change).

**Comment by ddeboer** [comment]
@sagikazarmark This is [done already](https://github.com/portphp/portphp/blob/master/.travis.yml#L17).

**Comment by sagikazarmark** [comment]
I meant the lowest version without deprecation

**Comment by ddeboer** [comment]
Okay, so only test against ~2.5?

**Comment by sagikazarmark** [comment]
2.5 or 2.7 where True constraint is replaced with IsTrue. See the symfony deprecation branch

**Comment by ddeboer** [comment]
@sagikazarmark When you open a branch, please also open a PR. Makes more sense to comment on PRs instead of issues when we’re working towards a solution.

**Comment by sagikazarmark** [comment]
Oh, didn't I open one? I wanted to...

**Comment by sagikazarmark** [comment]
Is it resolved then?

**Comment by ddeboer** [comment]
Yes. :)
