### ISSUE TITLE
How to import data between two databases where table structure differs

### ISSUE THREAD

**Issue by hirenchhatbar** [portphp/portphp#77]
Hello,

I'm trying to import data from db1.user table with below structure:

id
first_name
last_name

and want to import the same in db2.user table with below structure:

id
firstname
lastname

As you can notice that field name varies.

So I tried the same and got below error:

` [PDOException (42S22)]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'first_name' in 'field list'`

I'm using PdoReader and PdoWriter for the same.

Can you please help with and guide.

Thanks.

**Comment by hirenchhatbar** [comment]
Hi,

As far as I'm concerned, this would be real / practical situation where such would be happening and solution needed - it may that you've faced this earlier.

Many thanks.

**Comment by Baachi** [comment]
Hey @hirenchhatbar, as far as i undestood you. You want to read data from db1.user and import that data to db2.user and the only problem are the column names?

Then you can just use the `AS` feature from the database:

```php
$reader = new PdoReader($pdo, 'SELECT id, first_name AS firstname, last_name AS lastname FROM db1.user');
$writer = new PdoWriter($pdo, 'db2.user');
```

You can also use the [`MappingStep`](https://github.com/portphp/steps/blob/master/src/Step/MappingStep.php):

```php
$mapping = [
    'first_name' => 'firstname',
    'last_name' => 'lastname'
];

$workflow = new StepAggregator($reader);
$workflow->addStep(new MappingStep($mapping));
$workflow->addWriter($writer);
$workflow->process();
```
