### ISSUE TITLE
Item converters

### ISSUE THREAD

**Issue by icedevelopment** [portphp/portphp#79]
Hi,

I have used ddeboer/data-import a while ago on several projects with great success and I am now trying to use portphp on a new one.
One feature I regularly used in data-import were the Item converters which made it easy to transform items before writing them.
I have read in the documentation that these converters were removed.

How can I get similar functionality now?

For example: 
- How can I remap my item keys (MappingItemConverter) to the field names used in my doctrine entities?
- How can I transform my item values to other values (which was previously done using CallbackItemConverter)?

**Comment by aaa2000** [comment]
I think you can use `ConverterStep` http://portphp.readthedocs.io/en/latest/workflow/#mappingstep and `MappingStep` http://portphp.readthedocs.io/en/latest/workflow/#converterstep

**Comment by Baachi** [comment]
@aaa2000 is completly right. This functionality is not removed rather moved to the new step approach.

**Comment by icedevelopment** [comment]
Thanks!
