### ISSUE TITLE
Name for reader/writer packages

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#8]
Currently they are called portphp/doctrine, portphp/excel, portphp/pagerfanta and so on. Problem is that this makes them look a bit like forks from official packages like doctrine and pagerfanta. Should we rename the reader/writer packages to:

1. pagerfanta-plugin
1. pagerfanta-ship (in metaphor of ports)
1. pagerfanta-transfer
1. something else?

And if we choose a suffix, should it be reflected in the namespace as well?

**Comment by sagikazarmark** [comment]
I am against putting the suffix in the namespace. Like we don't put PHP in Port. Package names are one thing (like you said @ddeboer, we want to avoid confusion whether it is a fork or a custom package). Namespaces another.

**Comment by ddeboer** [comment]
5. pagerfanta-adapter?

**Comment by sagikazarmark** [comment]
Yeah, but if for some reasons we have to fork pagerfanta, we can't. I can't imagine too much cases when that would be necessary, but still...

**Comment by ddeboer** [comment]
portphp/pagerfanta-extension
portphp/pagerfanta-add-on

**Comment by Baachi** [comment]
I like the name `portphp/pagerfanta-adapter`. Its clear what the package contains.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by ddeboer** [comment]
@Baachi Do you agree this should not be reflected in the namespace?

`Port\PagerFantaAdapter\PagerfantaReader` 
`Port\Adapter\Pagerfanta\PagerfantaReader`
`Port\Pagerfanta\PagerfantaReader`

**Comment by sagikazarmark** [comment]
Hell, no. :stuck_out_tongue: 

It is mixing up package architecture with code.

**Comment by Baachi** [comment]
Yep a package name and namespaces are different things.

**Comment by ddeboer** [comment]
Agreed, I’ll rename the packages.

**Comment by sagikazarmark** [comment]
I don't think the core should support more than one excel adapter, so I think it is fine that way.
