### ISSUE TITLE
load function could append in doc file

### ISSUE THREAD

**Issue by HananAbulDahab** [portphp/portphp#82]
I use sample Sample_01_SimpleText.php I should change to html to save 
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'HTML');
 $objWriter->save('/var/www/html/helloWorld.doc');
My PC linux, PHP 7

the main problem in sample: Sample_11_ReadWord2007.php
I could not append in doc file I load then addSection then save by new name but no old data just new addsection data

[samples.zip](https://github.com/portphp/portphp/files/1883708/samples.zip)
file:///var/www/html/hello.doc.zip

**Comment by Baachi** [comment]
Hey @HananAbulDahab, i think you opened a issue on the wrong repository.
