### ISSUE TITLE
Steps 1.2.1 release bug: pipeline steps runs in the reverse order to 1.2.0

### ISSUE THREAD

**Issue by fusioned** [portphp/portphp#83]
I was just running with the latest release of Steps, 1.2.1, and the writer output with my test code changed unexpectedly.

The output looked the same as the input, as though all the mapping and conversions did not take place.

I looked for stepAggregator tests, but one that asserts pipeline execution order does not exist.

Looking at the differences between 1.2.0 and 1.2.1, this change stood out:
https://github.com/portphp/steps/commit/03f59ad3847b6dd6ee724fe12f50127e627b8035

It turns out replacing `StepAggregator.php` line 201:
        ```ksort($steps);```

with
        ```krsort($steps);```

solves the problem.

**Comment by Baachi** [comment]
Thank you for your reporting!

FIxed in `cd87c96`.
