### ISSUE TITLE
ValueConverter handle only one way

### ISSUE THREAD

**Issue by Baachi** [portphp/portphp#9]
Currently we have some filters which have a some valueconverters which can handle two convertions e.g.:

 * DateTimeValueConverter and DateTimeToStringValueConverter
 * ObjectConverter and StringToObjectConverter

Maybe its worth it to merge them together in some way (like symfony's [form component](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/DataTransformerInterface.php). 

Opinions and suggestions?

**Comment by sagikazarmark** [comment]
Since Converter interfaces are removed we are free to merge them into one object with whatever method names, but I think we should have either one convention (like in case of an interface: eg. transform/reverseTransform) or a straightforward one applied on each converter pair (like DateTimeValueConverter::toDateTime/toString).

Again, since interfaces are removed (and nothing implies that they should be reintroduced) the only place where we can declare this is the documentation, thus without an interface we do as we like.

**Comment by ddeboer** [comment]
How would that work when they are called through `__invoke()`?

**Comment by sagikazarmark** [comment]
Invoke is not important, steps accept callables. However in that case an interface would probably be better.

**Comment by Baachi** [comment]
Yep an interface would be the recommend way. Will work on it!

**Comment by sagikazarmark** [comment]
But if an interface is introduced for ValueConverters (again), will one be for Converters as well? Or are you gonna do this for converter "pairs"?

What about steps? Will they accept a callable or an instance of interface?

**Comment by ddeboer** [comment]
I kind of like the separation into multiple classes for doing the conversion one way (string -> date) and the other (date -> string): if you can divide a set of functionality into more classes, that’s a good thing. So actually I don’t see the benefit of an interface here. Converters can always extend an abstract base converter if they want to share functionality.

**Comment by sagikazarmark** [comment]
I think merging them into one makes sense, since they are doing exactly the reverse of the other, thus they have a connection. Since steps accept a callable (ATM), you can always pass the object with the desired function name.

**Comment by Baachi** [comment]
@sagikazarmark I don't want to have an interface for all converters, only for these which can transform a value in both ways (like the DateTimeConverer).

**Comment by ddeboer** [comment]
That’s confusing for users. Either all Converters implement an interface, or none does. I’m in favour of the latter, and to have separate converters for separate directions.

**Comment by Baachi** [comment]
I'm fine with the current implementation. I saw only room for optimization but i don't want to change the current implementation and reintroduce a new interface.

So i close this issue.
